plugins {
    id 'java'
    id 'build-dashboard'
    id 'project-report'
    id 'jacoco'
    id "org.springframework.boot" apply false
}

group = 'bao.doan'
version = '1.0-SNAPSHOT'

allprojects {
    apply plugin: "java"
    apply plugin: "jacoco"
    apply plugin: "build-dashboard"
    apply plugin: "project-report"

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation platform("org.springframework.boot:spring-boot-dependencies:$springBootVersion")
        annotationProcessor platform("org.springframework.boot:spring-boot-dependencies:$springBootVersion")
        testImplementation platform("org.springframework.boot:spring-boot-dependencies:$springBootVersion")
        testAnnotationProcessor platform("org.springframework.boot:spring-boot-dependencies:$springBootVersion")

        compileOnly "org.projectlombok:lombok"
        annotationProcessor "org.projectlombok:lombok"
        testCompileOnly "org.projectlombok:lombok"
        testAnnotationProcessor "org.projectlombok:lombok"
        testImplementation "org.junit.jupiter:junit-jupiter-api"
        testImplementation "org.junit.jupiter:junit-jupiter-params"
        testImplementation "org.assertj:assertj-core"
        testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
        testRuntimeOnly "org.junit.platform:junit-platform-launcher"
        compileOnly "org.mapstruct:mapstruct:$mapstructVersion"
        annotationProcessor "org.mapstruct:mapstruct-processor:$mapstructVersion"
    }
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(javaVersion)
        }
    }
    tasks.withType(JavaCompile) {
        if (!project.hasProperty("suppressWarnings")) {
            options.compilerArgs += ["-Werror", "-Xlint:all,-processing", "-parameters"]
        }
    }
    tasks.withType(Test) {
        useJUnitPlatform()
    }

    jacocoTestReport {
        dependsOn test
    }

    test {
        finalizedBy jacocoTestReport
    }

    tasks.withType(Test) {
        systemProperty "java.util.logging.config.file", "$projectDir/config/loggin.properties"
    }

    sourceSets {
        integrationTest {
            java.srcDir file("src/integrationTest/java")
            resources.srcDir file("src/integrationTest/resources")
            compileClasspath += sourceSets.main.output + configurations.testRuntimeClasspath
            runtimeClasspath += output + compileClasspath
        }
    }

    configurations {
        integrationTestImplementation.extendsFrom testImplementation
        integrationTestRuntimeOnly.extendsFrom testRuntimeOnly
    }

    tasks.register("integrationTest", Test) {
        description = "Runs integration tests."
        group = "verification"
        testClassesDirs = sourceSets.integrationTest.output.classesDirs
        classpath = sourceSets.integrationTest.runtimeClasspath
        shouldRunAfter test
        useJUnitPlatform()
    }

    check {
        dependsOn += jacocoTestCoverageVerification
        dependsOn += tasks.named("integrationTest")
    }

    jacoco {
        toolVersion = jacocoVersion
    }

    jacocoTestCoverageVerification {
        dependsOn jacocoTestReport
        violationRules {
            rule {
                limit {
                    minimum = 0.00
                }
            }
        }
    }
    test {
        useJUnitPlatform()
    }

}

dependencies {
    implementation(project(":app"))
    implementation(project(":product-domain"))
    implementation(project(":product-usecase"))
    implementation(project(":product-persistence"))
    implementation(project(":product-api"))
}

wrapper {
    gradleVersion = project.gradleVersion
    distributionType = "ALL"
}
