
pluginManagement {
    plugins {
        id "org.springframework.boot" version "$springBootVersion"
    }
    repositories {
        maven {
            url = "https://plugins.gradle.org/m2/"
        }
    }
}
rootProject.name = 'CleanArchitectDemo'

include ':app'
include ':product-domain'
include ':product-usecase'
include ':product-persistence'
include ':product-api'
