dependencies {
  implementation "jakarta.inject:jakarta.inject-api:$jakarktaInject"
  implementation "org.springframework:spring-context"
  implementation "org.hibernate.orm:hibernate-core"
  implementation "org.springframework.data:spring-data-jpa"
  implementation "org.mapstruct:mapstruct:$mapstructVersion"
  implementation "org.flywaydb:flyway-core"
  implementation(project(':product-domain'))
  testImplementation "org.springframework:spring-test"
  testImplementation "org.mockito:mockito-junit-jupiter"
  testImplementation "com.h2database:h2"
}
