spring:
  flyway:
    locations:
      - classpath:db/migration
    enabled: true
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/clean-architect
    username: user
    driver-class-name: com.mysql.cj.jdbc.Driver