spring:
  flyway:
    locations:
      - classpath:db/migration
    enabled: true
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver