dependencies {
    implementation "org.springframework:spring-webmvc"
    implementation "com.fasterxml.jackson.core:jackson-core"
    implementation "com.fasterxml.jackson.core:jackson-annotations"
    implementation "com.fasterxml.jackson.core:jackson-databind"
    implementation "jakarta.validation:jakarta.validation-api"
    implementation "org.mapstruct:mapstruct:$mapstructVersion"
    implementation(project(":product-domain"))
    implementation(project(":product-usecase"))
    testImplementation "org.springframework:spring-test"
    testImplementation "org.mockito:mockito-junit-jupiter"
    compileOnly "jakarta.servlet:jakarta.servlet-api"
    testImplementation "jakarta.servlet:jakarta.servlet-api"
    testImplementation "org.springframework.boot:spring-boot-autoconfigure"
    testImplementation "org.springframework.boot:spring-boot-test-autoconfigure"
    testImplementation "org.springframework.boot:spring-boot-webmvc-test"
}
